### ISSUE TITLE
Strange debounce feature in jsonform 

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#1170]
It seems that i can instantly trigger a change event when doing a single click/change (e.g. clicking on the slider directly to do a single value change). If i however change the value to rapidly (like within a second), e.g. by sliding or by consecutively changing the value, some sort of debounce delay happens which makes the update of the map (triggering of the change event) take like half a second or more). 
I tried to capture this in the animation below (it is a bit difficult without the mouse clicks).
I think instead of a debounce we should have a rate limit, so making sure the change event is not triggered more often then a number of times per second, but it should not completely stop propagating the change event, as it means nothing will update until the user stops changing values for at least a second.

[Screencast from 2024-07-31 14:49:22.webm](https://github.com/user-attachments/assets/def7fc99-66c5-44e6-b54b-e0059d11b528)

**Comment by silvester-pari** [comment]
I think the debounce actually does a rate limiting, but maybe the value is simply too high. This is actually set in the layer-config component of the layercontrol: https://github.com/EOX-A/EOxElements/blob/9d3b38c07c72802cfd44053b9b7955e6e1ac4fa2/elements/layercontrol/src/components/layer-config.js#L79

This was originally introduced in https://github.com/EOX-A/EOxElements/pull/656 because of an issue: https://github.com/EOX-A/EOxElements/issues/645

Probably we need to check if the "mode" is changing the WMS config or updating style variables; in the case of style variables the debounce can be much smaller or even be omitted probably.

**Comment by santilland** [comment]
If we want to "rate limit" we should probably use throttle and not debounce:
https://www.geeksforgeeks.org/lodash-_-throttle-method/
And 1 second debounce or throttle is quite high for any scenario, especially as default. I would reduce the default value by a lot (maybe like 150ms), potentially making it somehow configurable if necessary
