### ISSUE TITLE
Layer used for rendering selection features drops to bottom when resetting layer configuration of eox-map

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#1310]
The vector layer used for vector features "falls" to the bottom and can no longer be seen when setting the layers config of the eox-map afterwards.
The "hover" vector layer stays on top though, i think both should always stay on top of all other layers.
![Peek 2024-10-09 12-23](https://github.com/user-attachments/assets/bd141b35-ebf9-42b8-9c6d-801929d24a78)

**Comment by RobertOrthofer** [comment]
this looks like a bug that could very much be connected to the "layer-order-inside-groups"-problem, which should be fixed via https://github.com/EOX-A/EOxElements/pull/1321

The layer that includes the hovered or selected feature will always be on top, because we use the `setMap`-method of the layer to ensure this. However, I have encountered some real-world examples where the selectable layer was not quite at the top, e.g. when the user needs some absolutely crucial labels above the selectable layer to understand the data.

I have had bad experiences of using both the layer-array-index and the z-index of the layers to define the layer order of the map. This can lead to confusion between the devs and can obscure errors in the application... Ideally, the layer array order alone should be sufficient

**Comment by santilland** [comment]
If i understood correctly we actually have 3 layers, is this correct?:
* draw layer
* hover layer
* highlight layer
It seems these 3 have issues with ordering after updating the layer configuration of the map. I would propose for now to have high z-index values for now making sure that the ordering between these 3 layers is correct.
What do you think @silvester-pari ?
An alternative might be to have these 3 layers in a group and making sure that group always lives on top of all other groups?
I think we need to assume a position and for now that would be the top. Maybe we can somehow pass a configuration in the future that specifies on what level this group should be?

**Comment by silvester-pari** [comment]
We actually "have" only one layer, the selection vector feature layer. The selection styling (both hover and/or click) is added as a **temporary** layer which is **always** on top.

From my point of view it is ok to set the selection vector feature layer to a very high zIndex inside `eox-drawtools` (and document it somewhere). If we really have a situation where e.g. a labels layer needs to be on top of the selection vector feature layer, then we can simply set that labels layer to the zIndex + 1.

In the `eox-map` no change is needed I guess, since there you can simply put the selection vector feature layer in the correct order as wanted. It's just that in drawtools we have an "opinion" on where it should live.

Would you agree with such a procedure?

**Comment by RobertOrthofer** [comment]
I am not very familiar with the `eox-drawtools`, I suppose it creates a vector layer to be drawn to, and adds a select interaction to select the previously drawn features?

I am still not 100% confident what the actual desired behaviour is: 
 - the "hover"-layer is always on top even when the vector-layer is further down
 => this is expected, I suppose the "hover/select" interaction could be temporarily disabled when moving the layer down, if that is a problem
 - the layer used for vector features "falls" to the bottom and can no longer be seen when setting the layers config of the eox-map afterwards
     => this seems like a bug that needs investigation

**Comment by silvester-pari** [comment]
@santilland could you try out the proposed solution from #1344 if that solves your issue (or at least parts of it)? You can use the dev package `@eox/drawtools@0.11.1-dev.1730225750.0`.
