### ISSUE TITLE
Implement event callback for change in layer visibility in LayerControl element

### ISSUE THREAD

**Issue by viktoraronfarkas** [EOX-A/EOxElements#647]
When the visibility of the layers are changed, and event callback could be useful, if the user wants to bind some custom functionality to changing the layer visibility.

**Comment by StefanBrand** [comment]
There is actually a map event for the layer visibility. We implement an event handler here similar to this:

```js
const olLayer = document.querySelector("eox-map").getLayerById(layerId);
olLayer.on("change:visible", onLayerChangeVisible;
```

**Comment by silvester-pari** [comment]
I think the idea proposed in this issue is that one has not to loop over all layers manually and set a listener, which could come in handy.

On the other hand, we had more than once the question of how to "select" a layer; this concept is something we could consider (and discuss in a separate issue).
